---
masters:
  - name: lava-master-local
    host: local
    users:
      - name: ${LAVA_USER}
        password: ${LAVA_PASSWORD}
        token: admin-token
        superuser: true
        staff: true
    tokens:
      - username: ${LAVA_USER}
        token: ${LAVA_TOKEN}
        description: ${LAVA_TOKEN_DESCRIPTION}
    write_dot_env: True
    webinterface_port: 10070
slaves:
  - name: lava-slave-local
    host: local
    remote_master: lava-master-local
    remote_user: ${LAVA_USER}
    use_docker: true

boards:
  - name: qemu-01
    type: qemu

